# Generated by Django 5.2.5 on 2025-08-09 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social del cliente', max_length=200, verbose_name='Nombre/Razón Social')),
                ('cuit', models.CharField(help_text='CUIT en formato XX-XXXXXXXX-X', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El CUIT debe tener el formato XX-XXXXXXXX-X', regex='^\\d{2}-\\d{8}-\\d{1}$')], verbose_name='CUIT')),
                ('domicilio', models.TextField(blank=True, help_text='Dirección completa del cliente', null=True, verbose_name='Domicilio')),
                ('clave_fiscal', models.CharField(blank=True, help_text='Clave de acceso a AFIP', max_length=100, null=True, verbose_name='Clave Fiscal')),
                ('clave_ciudad', models.CharField(blank=True, help_text='Clave de acceso a sistemas de CABA', max_length=100, null=True, verbose_name='Clave Ciudad')),
                ('clave_arba', models.CharField(blank=True, help_text='Clave de acceso a ARBA', max_length=100, null=True, verbose_name='Clave ARBA')),
                ('clave_sec', models.CharField(blank=True, help_text='Clave de acceso a SEC', max_length=100, null=True, verbose_name='Clave SEC')),
                ('clave_faecys', models.CharField(blank=True, help_text='Clave de acceso a FAECYS', max_length=100, null=True, verbose_name='Clave FAECYS')),
                ('clave_inacap', models.CharField(blank=True, help_text='Clave de acceso a INACAP', max_length=100, null=True, verbose_name='Clave INACAP')),
                ('clave_osecac', models.CharField(blank=True, help_text='Clave de acceso a OSECAC', max_length=100, null=True, verbose_name='Clave OSECAC')),
                ('clave_rubrica_digital_caba', models.CharField(blank=True, help_text='Clave de acceso a Rúbrica Digital CABA', max_length=100, null=True, verbose_name='Clave Rúbrica Digital CABA')),
                ('clave_estudio_one_web', models.CharField(blank=True, help_text='Clave de acceso a Estudio One Web', max_length=100, null=True, verbose_name='Clave Estudio One Web')),
                ('registro_de_empleadores', models.CharField(blank=True, help_text='Número de registro de empleadores', max_length=100, null=True, verbose_name='Registro de Empleadores')),
                ('otros_datos', models.TextField(blank=True, help_text='Información adicional del cliente', null=True, verbose_name='Otros Datos')),
                ('carpeta', models.CharField(blank=True, help_text='Ubicación de carpeta física o digital', max_length=200, null=True, verbose_name='Carpeta')),
                ('ptovta', models.CharField(blank=True, help_text='Punto de venta asignado', max_length=50, null=True, verbose_name='Punto de Venta')),
                ('nombase', models.CharField(blank=True, help_text='Nombre de base de datos', max_length=200, null=True, verbose_name='Nombre Base')),
                ('ruta_base', models.CharField(blank=True, help_text='Ruta de la base de datos', max_length=500, null=True, verbose_name='Ruta Base')),
                ('rutabackup', models.CharField(blank=True, help_text='Ruta de respaldo', max_length=500, null=True, verbose_name='Ruta Backup')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
